# Generated by Django 5.2.8 on 2026-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0004_marathondaytracking_workoutexercisetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='food_name',
            field=models.CharField(max_length=255),
        ),
    ]
